import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { getAirportsByCodes } from './queries';
import type { AirportRouteMap, RouteDestination } from './types';
import { localizedPath, type Locale } from './i18n/config';

/**
 * Route data for the airport page's route map.
 *
 * `data/airport-routes.json` is generated by scripts/fetch-routes.mjs from the
 * OpenFlights dump (ODbL — a 2014-06 snapshot, which is why the page prints the
 * data date) and lists, per source airport, the destinations it serves plus the
 * carriers on each one. Destination coordinates and English place names are
 * joined in from public/data/world-airports.json (the same index the homepage
 * map draws from); destinations the directory itself covers get the site's own
 * translated name, city and country instead, and the rest stay in English —
 * exactly how the bulk OurAirports data is shown everywhere else.
 *
 * Server-only: the route file is ~1.7 MB and is read from disk, never shipped to
 * the browser. Client components import lib/route-tiers.ts for the colour scale.
 */

type RawRouteEntry = { iata: string; km: number; carriers: string[] };

type RawRoutesFile = {
  meta: { source: string; sourceUrl: string; license: string; dataDate: string; generatedAt: string };
  /** Carrier code -> airline name; codes upstream cannot name are absent. */
  airlines: Record<string, string>;
  airports: Record<string, { lat: number; lng: number; destinations: RawRouteEntry[] }>;
};

type WorldAirport = { name: string; city: string; country: string; iso2: string; lat: number; lng: number };

/** Row shape of public/data/world-airports.json (see scripts/prepare-world-airports.mjs). */
type WorldAirportsFile = {
  airports: [string, string, string, string, string, string, number, number, number][];
};

let routesCache: RawRoutesFile | null = null;
let worldCache: Map<string, WorldAirport> | null = null;

/** Reads the generated route file once per worker; a missing file disables the section. */
function loadRoutes(): RawRoutesFile | null {
  if (routesCache) return routesCache;
  try {
    routesCache = JSON.parse(
      readFileSync(join(process.cwd(), 'data', 'airport-routes.json'), 'utf8')
    ) as RawRoutesFile;
  } catch {
    console.warn('data/airport-routes.json is missing — run `node scripts/fetch-routes.mjs`');
    return null;
  }
  return routesCache;
}

/** IATA -> name/city/country/coordinates index of every scheduled-service airport. */
function loadWorldAirports(): Map<string, WorldAirport> {
  if (!worldCache) {
    const file = JSON.parse(
      readFileSync(join(process.cwd(), 'public', 'data', 'world-airports.json'), 'utf8')
    ) as WorldAirportsFile;
    worldCache = new Map(
      file.airports.map(([iata, name, city, country, iso2, , lat, lng]) => [
        iata,
        { name, city, country, iso2, lat, lng },
      ])
    );
  }
  return worldCache;
}

/**
 * Direct-destination count per source airport, from the route dump. Synchronous
 * and database-free so the homepage can rank the airport summaries it has
 * already loaded instead of running another query.
 */
export function routeDestinationCounts(): Map<string, number> {
  const file = loadRoutes();
  const counts = new Map<string, number>();
  if (!file) return counts;
  for (const [iata, entry] of Object.entries(file.airports)) {
    counts.set(iata, entry.destinations.length);
  }
  return counts;
}

/**
 * IATA codes the route dump actually covers. The standalone route pages are
 * built and linked for this set only (intersected with the directory's own
 * airports by the caller), so no URL ships an empty map. Reads the generated
 * file without touching the database.
 */
export function routeAirportCodes(): string[] {
  const file = loadRoutes();
  return file ? Object.keys(file.airports) : [];
}

/**
 * Figures derived from one airport's route map, shared by the route page's
 * header cells and its FAQ so the two can never disagree.
 */
export type RouteStats = {
  destinationCount: number;
  /** Distinct carriers across every destination. */
  airlineCount: number;
  /** Distinct destination countries. */
  countryCount: number;
  /** Farthest destination by great-circle distance. */
  farthest: RouteDestination | null;
  /** Destinations served by three or more airlines, busiest first. */
  busiest: RouteDestination[];
  /** Carriers ranked by how many destinations they serve. */
  topCarriers: { name: string; destinations: number }[];
};

export function routeStats(map: AirportRouteMap): RouteStats {
  const carriers = new Set<string>();
  const countries = new Set<string>();
  const perCarrier = new Map<string, number>();
  let farthest: RouteDestination | null = null;

  for (const destination of map.destinations) {
    countries.add(destination.countryCode);
    if (!farthest || destination.km > farthest.km) farthest = destination;
    for (const carrier of destination.carriers) {
      carriers.add(carrier.code);
      perCarrier.set(carrier.name, (perCarrier.get(carrier.name) ?? 0) + 1);
    }
  }

  return {
    destinationCount: map.destinations.length,
    airlineCount: carriers.size,
    countryCount: countries.size,
    farthest,
    busiest: map.destinations.filter((destination) => destination.carriers.length >= 3),
    topCarriers: [...perCarrier.entries()]
      .map(([name, destinations]) => ({ name, destinations }))
      .sort((a, b) => b.destinations - a.destinations || a.name.localeCompare(b.name))
      .slice(0, 3),
  };
}

/**
 * The route map for one airport, or null when the dump has no routes for it
 * (or the generated file is absent) — callers then simply skip the section.
 */
export async function getAirportRouteMap(
  locale: Locale,
  iata: string
): Promise<AirportRouteMap | null> {
  const file = loadRoutes();
  if (!file) return null;
  const raw = file.airports[iata.toUpperCase()];
  if (!raw || raw.destinations.length === 0) return null;

  const world = loadWorldAirports();
  const destinations: RouteDestination[] = [];
  for (const entry of raw.destinations) {
    const place = world.get(entry.iata);
    // The dump only keeps destinations both indexes know, so this guards
    // nothing but a stale generated file.
    if (!place) continue;
    destinations.push({
      iata: entry.iata,
      name: place.name,
      city: place.city,
      country: place.country,
      countryCode: place.iso2,
      lat: place.lat,
      lng: place.lng,
      km: entry.km,
      carriers: entry.carriers.map((code) => ({
        code,
        name: file.airlines[code] ?? code,
      })),
    });
  }
  if (destinations.length === 0) return null;

  // One query for every destination the directory knows, then the Chinese (or
  // English) names override the bulk index per destination.
  const covered = await getAirportsByCodes(
    locale,
    destinations.map((d) => d.iata)
  );
  const byIata = new Map(covered.map((airport) => [airport.iata, airport]));
  for (const destination of destinations) {
    const hit = byIata.get(destination.iata);
    if (!hit) continue;
    destination.name = hit.name;
    destination.city = hit.city;
    destination.country = hit.countryName;
    // A destination the directory covers is also a destination the map can
    // click through to; the rest stay plain markers with a tooltip.
    destination.href = localizedPath(locale, `/airport/${hit.iata}`);
  }

  return {
    lat: raw.lat,
    lng: raw.lng,
    destinations,
    dataDate: file.meta.dataDate,
    source: { name: file.meta.source, url: file.meta.sourceUrl, license: file.meta.license },
  };
}
