import { readdirSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Static route-map renders shipped in /public/route, keyed by IATA code
 * (FRA.png) and generated by scripts/generate-route-images.mjs. The directory
 * is read once per process and cached — rerunning the generator under a live
 * dev server needs a server restart (or a code change) to refresh it.
 * Server-side only: never import this from a client component.
 */
let filenames: Set<string> | null = null;

function available(): Set<string> {
  if (!filenames) {
    try {
      filenames = new Set(readdirSync(join(process.cwd(), 'public', 'route')));
    } catch {
      filenames = new Set();
    }
  }
  return filenames;
}

/** `/route/FRA.png` when a render exists for the code, else null. */
export function routeImageUrl(iata: string): string | null {
  const file = `${iata.toUpperCase()}.png`;
  return available().has(file) ? `/route/${file}` : null;
}
