import { DownloadIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { getMessages } from '@/lib/i18n';
import type { Locale } from '@/lib/i18n/config';
import type { AirportRouteMap } from '@/lib/types';

/**
 * "Data download" row: the destinations behind the map as CSV (spreadsheets)
 * or JSON (scripts), generated by /api/routes/<IATA>. Plain anchors carrying a
 * `download` attribute, so they work without JavaScript.
 *
 * The green/blue button treatment matches the terminal-map downloads on the
 * airport page (components/airport/MapDownloads.tsx).
 */
const GREEN =
  'max-sm:w-full gap-[9px] rounded-[10px] bg-[#1E8E4B] font-bold text-white shadow-[0_8px_18px_-10px_rgba(30,142,75,0.85)] hover:bg-[#1E8E4B] hover:brightness-110';
const BLUE =
  'max-sm:w-full gap-[9px] rounded-[10px] bg-[#0D6EFD] font-bold text-white shadow-[0_8px_18px_-10px_rgba(13,110,253,0.85)] hover:bg-[#0D6EFD] hover:brightness-110';

export default function RouteDataDownloads({
  locale,
  iata,
  map,
}: {
  locale: Locale;
  iata: string;
  map: AirportRouteMap;
}) {
  const t = getMessages(locale);
  const icon = <DownloadIcon className="opacity-95" />;

  return (
    <>
      <div className="map-dl-row">
        <Button asChild size="lg" className={GREEN}>
          <a href={`/api/routes/${iata}?locale=${locale}&format=csv`} download={`${iata}-routes.csv`}>
            {icon}
            {t.route.dataCsv}
          </a>
        </Button>
        <Button asChild size="lg" className={BLUE}>
          <a href={`/api/routes/${iata}?locale=${locale}&format=json`} download={`${iata}-routes.json`}>
            {icon}
            {t.route.dataJson}
          </a>
        </Button>
      </div>
      <p className="ext-note">{t.route.dataFields}</p>
      <p className="ext-note">{t.route.dataSub(map.destinations.length)}</p>
    </>
  );
}
